name: Build and Publish image to Docker Hub

on:
    [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    environment: staging
    env:
       IMG_NAME: juliorbt1/sjbeservicezipunzipfile  
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: login docker
          uses: docker/login-action@v3
          with:
            username: ${{ vars.USERNAME_DOCKER }}
            password: ${{ secrets.PASSWORD_DOCKER }}

        - name: build image
          run: docker buildx build -t ${{env.IMG_NAME}}:${{vars.VERSION_IMAGE_TAG}} .

        - name: push image to docker hub
          run: docker push ${{env.IMG_NAME}}:${{vars.VERSION_IMAGE_TAG}}

  deploy:
    name: Deploy service to server
    needs: build
    runs-on: self-hosted
    environment: staging
    env:
      IMG_NAME: juliorbt1/sjbeservicezipunzipfile
    steps:
      - name: Deploy service to server
        run: sudo docker rm -f ${{vars.CONTAINER_NAME}}-${{env.TAGS}} || true
      
      - name: Run container
        run: sudo docker run -d -p 8080:8080 --restart always --name ${{vars.CONTAINER_NAME}}-${{vars.VERSION_IMAGE_TAG}} ${{env.IMG_NAME}}:${{vars.VERSION_IMAGE_TAG}} 


        
