name: Docker Image Build Publish

on:
    [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    env:
       IMG_NAME: juliorbt1/sjbeservicezipunzipfile  
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: login docker
          uses: docker login -u ${{env.USERNAME_DOCKER}} -p ${{env.PASSWORD_DOCKER}}

        - name: build image
          run: docker buildx build -t ${{env.IMG_NAME}}:${{env.VERSION_IMAGE_TAG}} .

        - name: push image to docker hub
          run: docker push ${{env.IMG_NAME}}:${{env.VERSION_IMAGE_TAG}}
